### ISSUE TITLE
formidable.parse callback called multiple times

### ISSUE THREAD

**Issue by mroshko** [noraesae/express-formidable#6]
The current implementation of the express-formidable middleware.js file uses a single, shared formidable.IncomingForm object (i.e. 'form').

A consequence of this is that each time it calls form.parse(), the IncomingForm object initialises itself with another set of event handlers for the field, file, end, etc. events.  

The end result is that each time an event is emitted, the event handler for it is called multiple times.  The ultimate effect of this is that the express-formidable callback given to form.parse() gets called multiple times, leading to multiple calls to next() and strange behaviour...

It is easy to reproduce with the attached app.js file as server and client requests coming from something like "curl -XPOST http://localhost:3000/user -d 'name=value'"

I added some logging to express-formidable/lib/middleware.js and to formidable/lib/incoming_form.js to track the number of 'field' event handlers registered on the IncomingForm instance.  This shows the error in action as can be seen below.

After a single curl -XPOST http://localhost:3000/user -d 'name=value':
```
[2016-10-13T14:04:56.493Z]  INFO: vfserver/42713 on macs-MacBook-Pro.local: express-formidable middleware start
[2016-10-13T14:04:56.496Z]  INFO: vfserver/42713 on macs-MacBook-Pro.local:    IncomingForm.parse() field event handlers at entry: []
[2016-10-13T14:04:56.499Z]  INFO: vfserver/42713 on macs-MacBook-Pro.local:    IncomingForm.parse() field event handlers at exit: [ [Function] ]
[2016-10-13T14:04:56.502Z]  INFO: vfserver/42713 on macs-MacBook-Pro.local:    urlEncoded parser emitting field event: name value
[2016-10-13T14:04:56.503Z]  INFO: vfserver/42713 on macs-MacBook-Pro.local:     --> IncomingForm handling field event: name value
[2016-10-13T14:04:56.503Z]  INFO: vfserver/42713 on macs-MacBook-Pro.local:    urlEncoded parser emitting end event
[2016-10-13T14:04:56.503Z]  INFO: vfserver/42713 on macs-MacBook-Pro.local:     --> IncomingForm handling end event
[2016-10-13T14:04:56.503Z]  INFO: vfserver/42713 on macs-MacBook-Pro.local: express-formidable middleware: formidable.parse() callback
```
So just one set of event handlers and everything is fine.

But after a second curl -XPOST http://localhost:3000/user -d 'name=value':

```
[2016-10-13T14:05:02.038Z]  INFO: vfserver/42713 on macs-MacBook-Pro.local: express-formidable middleware start
[2016-10-13T14:05:02.039Z]  INFO: vfserver/42713 on macs-MacBook-Pro.local:    IncomingForm.parse() field event handlers at entry: [ [Function] ]
[2016-10-13T14:05:02.039Z]  INFO: vfserver/42713 on macs-MacBook-Pro.local:    IncomingForm.parse() field event handlers at exit: [ [Function], [Function] ]
[2016-10-13T14:05:02.040Z]  INFO: vfserver/42713 on macs-MacBook-Pro.local:    urlEncoded parser emitting field event: name value
[2016-10-13T14:05:02.040Z]  INFO: vfserver/42713 on macs-MacBook-Pro.local:     --> IncomingForm handling field event: name value
[2016-10-13T14:05:02.040Z]  INFO: vfserver/42713 on macs-MacBook-Pro.local:     --> IncomingForm handling field event: name value
[2016-10-13T14:05:02.041Z]  INFO: vfserver/42713 on macs-MacBook-Pro.local:    urlEncoded parser emitting end event
[2016-10-13T14:05:02.041Z]  INFO: vfserver/42713 on macs-MacBook-Pro.local:     --> IncomingForm handling end event
[2016-10-13T14:05:02.041Z]  INFO: vfserver/42713 on macs-MacBook-Pro.local: express-formidable middleware: formidable.parse() callback
[2016-10-13T14:05:02.042Z]  INFO: vfserver/42713 on macs-MacBook-Pro.local:     --> IncomingForm handling end event
[2016-10-13T14:05:02.042Z]  INFO: vfserver/42713 on macs-MacBook-Pro.local: express-formidable middleware: formidable.parse() callback
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (/Users/mac/development/node/vfserver/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/Users/mac/development/node/vfserver/node_modules/express/lib/response.js:163:12)
    at /Users/mac/development/node/vfserver/app.js:15:7
    at Layer.handle [as handle_request] (/Users/mac/development/node/vfserver/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/mac/development/node/vfserver/node_modules/express/lib/router/index.js:312:13)
    at /Users/mac/development/node/vfserver/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/mac/development/node/vfserver/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/mac/development/node/vfserver/node_modules/express/lib/router/index.js:271:10)
    at /Users/mac/development/node/vfserver/node_modules/express-formidable/lib/middleware.js:22:7
```
As you can see, now there are two of each event handler which means each event is handled twice, leading to two next() calls and hence an exception about headers being set too late.

A third client request ends up showing 3 event handlers registered and so on.  Eventually the server would probably crash once the array of event handlers grows too large.

**Suggested Solution:**

I tried simply moving the creation of 'form' to within the middleware function itself (as shown below) and that seemed to do the trick.

```
*** 1,14 ****
  'use strict';
  
  const formidable = require('formidable');
  
  function parse(opts) {
-   const form = new formidable.IncomingForm();
-   Object.assign(form, opts);
- 
    return (req, res, next) => {
      form.parse(req, (err, fields, files) => {
        if (err) {
          next(err);
          return;
        }
--- 1,14 ----
  'use strict';
  
  const formidable = require('formidable');
  
  function parse(opts) {
    return (req, res, next) => {
+     const form = new formidable.IncomingForm();
+     Object.assign(form, opts);
+ 
      form.parse(req, (err, fields, files) => {
        if (err) {
          next(err);
          return;
        }
```

Best Regards,
Mike

[app.js.txt](https://github.com/noraesae/express-formidable/files/527379/app.js.txt)

**Comment by vivasaayi** [comment]
If you make parallel requests, you will get this exceptions immediately.

**Comment by gpascale** [comment]
Simple example to show how ridiculously broken this library is right now. Just making a second request while one is in flight will cause the first one to 404 and then try to send twice.

```
const express = require('express');
const morgan = require('morgan');
const formidable = require('express-formidable');
const app = express();

app.listen(3000, function() {
  console.log('Server started on port 3000');
});

app.use(morgan('dev'));
app.use(formidable());

app.get('/api/myroute', function(req, res) {
  console.log('/api/myroute ' + req.query.id);
  setTimeout(() => {
    res.status(200).send('Ok!\n').end();
  }, 5000);
});
```

curl http://localhost:3000?id=1
... wait one second
curl http://localhost:3000?id=2

![image](https://user-images.githubusercontent.com/325055/27013595-66d62244-4eac-11e7-8e60-435bbb46468c.png)

**Comment by sonuharikot** [comment]
Removed express-formidable and install  formidable only and add below code in app.js

app.use(function (req, res, next) {
    var form = new formidable.IncomingForm({
        encoding: 'utf-8',
        uploadDir: './tmp',
        multiples: true,
        keepExtensions: true
    })
    form.once('error', console.log)
    form.parse(req, function (err, fields, files) {
        Object.assign(req, {fields, files});
        next();
    })
})

**Comment by unitof** [comment]
For me, the number of `Can't set headers after they are sent.` errors didn't increment with each client request, but I did get one per request, every time, starting with the second. The error was definitely caused by Formidable, and I tried some of the other Middleware arrangements suggested in https://github.com/utatti/express-formidable/issues/1#issuecomment-251713907. All with identical results. For example:

```js
router.post('*', formidable(), function(req, res, next) {
  console.log('Uplink receiving transmision...');
  console.log('req.fields:', req.fields);
  console.log('req.files:', req.files);
  res.send('Success!\n');
});
```

What worked was, as @sonuharikot suggested, switching from `express-formidable` to straight-up `formidable`, then routing all relevant requests through it and invoking `next()` to pass onto my personal routing functions.

Thing is, I only need Formidable for a `POST`s to a single route on my site (`/upload`), so here's my implementation, should any desperate Googlers such as myself one hour before now find it useful:

```js
router.post('/upload', (function (req, res, next) {
  var form = new formidable.IncomingForm();
  form.once('error', console.log);
  form.parse(req, function (err, fields, files) {
    Object.assign(req, {fields, files});
    next();
  });
}));
```

**Comment by Kequc** [comment]
I also wanted my files cleaned up after every request, so this is the middleware that works for me.

```javascript
const fs = require('fs-extra');
const formidable = require('formidable');

module.exports = (req, res, next) => {
    const form = new formidable.IncomingForm();

    form.parse(req, (err, fields, files) => {
        if (err) { next(err); return; }

        function cleanupFiles () {
            res.removeListener('finish', cleanupFiles);
            res.removeListener('close', cleanupFiles);
    
            for (const key of Object.keys(files)) {
                fs.remove(files[key].path).catch(() => {});
            }
        }
    
        res.on('finish', cleanupFiles);
        res.on('close', cleanupFiles);
    
        Object.assign(req, { fields, files });

        next();
    });
};
```

Finish is triggered when the request was successful and close is triggered when something has failed. The bug described in the op was driving me crazy.

**Comment by sufrimendaa** [comment]
Oh my God. I wasted so much time on this. I didn't know what is causing this strange error, was looking in completely different places. Please update the library to save the time of other developers!

**Comment by Prinzhorn** [comment]
Can be closed as well, fixed in 1.2.0 https://github.com/utatti/express-formidable/issues/18#issuecomment-438715315
