### ISSUE TITLE
TypeError: this._parser.write is not a function

### ISSUE THREAD

**Issue by boardgames** [noraesae/express-formidable#9]
client:

  var data = new FormData();

  data.append( 'input', this.inputFile.files[ 0 ], this.inputFile.files[ 0 ].name );

  var xhr = new XMLHttpRequest();
  
  xhr.open( 'POST', REST_API_URL, true );
  xhr.setRequestHeader( 'content-type', 'multipart/form-data' );
  xhr.send( data );

server:

    app.use( formidable( {
      encoding: 'utf-8',
      uploadDir: './temp',
    } ) );

Error:

TypeError: this._parser.write is not a function
    at IncomingForm.write (/Users/Miloserdov/Projects/swf-parser/node_modules/formidable/lib/incoming_form.js:157:34)
    at IncomingMessage.<anonymous> (/Users/Miloserdov/Projects/swf-parser/node_modules/formidable/lib/incoming_form.js:123:12)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:188:7)
    at IncomingMessage.Readable.read (_stream_readable.js:381:10)
    at flow (_stream_readable.js:761:34)
    at resume_ (_stream_readable.js:743:3)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by stellardb** [comment]
I got a similar error. Any idea what causes this? Maybe headers being parsed incorrectly?

**Comment by stellardb** [comment]
In my case, a header was missing for the request: `content-type`.

So I think this issue should not come up when both of these headers are present: `content-type` and `content-length`.
